#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\Views\Report\calender.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    
    #line 1 "..\..\Views\Report\calender.cshtml"
    using System.Threading;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using KneaderPrototype;
    using KneaderPrototype.Controllers;
    
    #line 3 "..\..\Views\Report\calender.cshtml"
    using KneaderPrototype.Report.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Report/calender.cshtml")]
    public partial class _Views_Report_calender_cshtml : System.Web.Mvc.WebViewPage<KneaderPrototype.Report.Models.DataReportModel>
    {
        public _Views_Report_calender_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Views\Report\calender.cshtml"
  
    ViewBag.Title = "calender";
    string name = string.Empty;
    int EndType = 0;
    int amntTotal = 0;
    int amntOverall = 0;
    int amnt = 0;
    string colourRow = "white";
    int count = 0;
    int countOverall = 0;
    int dosingOutCount = 0;
    int dosingOutAmountSum = 0;
    int rowDOcount = 0;
    int rowDOamount = 0;
    int rowDOcountOverall = 0;
    int rowDOamountOverall = 0;
    int cleaningCount = 0;
    /*
    int rowDOcount = 0;
    int rowDOamount = 0;
    int rowDOcountOverall = 0;
    int rowDOamountOverall = 0;
    */
    int year = ViewBag.year;
    int yearOnButtonLeft = year;
    int yearOnButtonRight = year;
    int monthLess = ViewBag.Month - 1;
    int monthMore = ViewBag.Month + 1;
    if (monthLess < 1)
    {
        yearOnButtonLeft--;
        monthLess = 12;
    }
    if (monthMore > 12)
    {
        yearOnButtonRight++;
        monthMore = 1;
    }
    ViewHeaderDosingOut dosingOut = null;
    ViewHeaderCleaning cleaning = null;
    Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");
    DateTime monthDT = new DateTime(year, ViewBag.month, 1);
    string monthName = monthDT.ToString("MMMM");


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h4>Calender</h4>\r\n<div");

WriteLiteral(" class=\" col-md-12\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" class=\"btn-primary btn-xs\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1445), Tuple.Create("\"", 1494)
, Tuple.Create(Tuple.Create("", 1452), Tuple.Create("/Report/Month/", 1452), true)
            
            #line 54 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 1466), Tuple.Create<System.Object, System.Int32>(monthLess
            
            #line default
            #line hidden
, 1466), false)
, Tuple.Create(Tuple.Create("", 1476), Tuple.Create("/", 1476), true)
            
            #line 54 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 1477), Tuple.Create<System.Object, System.Int32>(yearOnButtonLeft
            
            #line default
            #line hidden
, 1477), false)
);

WriteLiteral(">-1 month</a> Month: ");

            
            #line 54 "..\..\Views\Report\calender.cshtml"
                                                                                                   Write(monthName);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 54 "..\..\Views\Report\calender.cshtml"
                                                                                                              Write(year);

            
            #line default
            #line hidden
WriteLiteral(" <a");

WriteLiteral(" class=\"btn-primary btn-xs\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1562), Tuple.Create("\"", 1612)
, Tuple.Create(Tuple.Create("", 1569), Tuple.Create("/Report/Month/", 1569), true)
            
            #line 54 "..\..\Views\Report\calender.cshtml"
                                                                                           , Tuple.Create(Tuple.Create("", 1583), Tuple.Create<System.Object, System.Int32>(monthMore
            
            #line default
            #line hidden
, 1583), false)
, Tuple.Create(Tuple.Create("", 1593), Tuple.Create("/", 1593), true)
            
            #line 54 "..\..\Views\Report\calender.cshtml"
                                                                                                      , Tuple.Create(Tuple.Create("", 1594), Tuple.Create<System.Object, System.Int32>(yearOnButtonRight
            
            #line default
            #line hidden
, 1594), false)
);

WriteLiteral(">+1 month</a>\r\n    <p></p>\r\n</div>\r\n<div");

WriteLiteral(" class=\" col-md-12\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"checkbox-inline big-checkbox\"");

WriteLiteral(">\r\n        <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" onclick=\"hideShowBatches()\"");

WriteLiteral(" />Hide/Show Batches\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"checkbox-inline big-checkbox\"");

WriteLiteral(">\r\n        <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" onclick=\"hideShowDosing()\"");

WriteLiteral(" checked />Hide/Show Dosing\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"checkbox-inline big-checkbox\"");

WriteLiteral(">\r\n        <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" onclick=\"hideShowCleaning()\"");

WriteLiteral(" checked />Hide/Show Cleaning\r\n    </div>\r\n</div>\r\n<table");

WriteLiteral(" class=\"table-bordered table-condensed\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n            <th>Day | Hours</th>\r\n");

            
            #line 72 "..\..\Views\Report\calender.cshtml"
            
            
            #line default
            #line hidden
            
            #line 72 "..\..\Views\Report\calender.cshtml"
             for (int hours = 0; hours < 24; hours++)
            {

            
            #line default
            #line hidden
WriteLiteral("                <th");

WriteLiteral(" class=\"th-Report\"");

WriteLiteral(">");

            
            #line 74 "..\..\Views\Report\calender.cshtml"
                                 Write(hours);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n");

            
            #line 75 "..\..\Views\Report\calender.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <th");

WriteLiteral(" style=\"background-color: lightcyan;\"");

WriteLiteral(" title=\"Batches Count\"");

WriteLiteral(">B. cnt.</th>\r\n            <th");

WriteLiteral(" style=\"background-color: lightcyan;\"");

WriteLiteral(" title=\"Dosing Count\"");

WriteLiteral(">DO. cnt.</th>\r\n            <th");

WriteLiteral(" style=\"background-color: lightgray;\"");

WriteLiteral(" title=\"Batches amount\"");

WriteLiteral(">B. amt.</th>\r\n            <th");

WriteLiteral(" style=\"background-color: lightgray;\"");

WriteLiteral(" title=\"Dosing amount\"");

WriteLiteral(">DO. amt.</th>\r\n        </tr>\r\n    </thead>\r\n");

            
            #line 82 "..\..\Views\Report\calender.cshtml"
    
            
            #line default
            #line hidden
            
            #line 82 "..\..\Views\Report\calender.cshtml"
     for (int day = 1; day <= DateTime.DaysInMonth(year, ViewBag.month); day++)
    {
        
            
            #line default
            #line hidden
            
            #line 84 "..\..\Views\Report\calender.cshtml"
           DateTime dayDT = new DateTime(year, ViewBag.month, day); string sDay = dayDT.DayOfWeek.ToString();  
            
            #line default
            #line hidden
            
            #line 84 "..\..\Views\Report\calender.cshtml"
                                                                                                                

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n");

            
            #line 86 "..\..\Views\Report\calender.cshtml"
                
            
            #line default
            #line hidden
            
            #line 86 "..\..\Views\Report\calender.cshtml"
                 if (dayDT.DayOfWeek == DayOfWeek.Saturday || dayDT.DayOfWeek == DayOfWeek.Sunday)
                {
                    colourRow = "lightgoldenrodyellow";

            
            #line default
            #line hidden
WriteLiteral("                    <td>");

            
            #line 89 "..\..\Views\Report\calender.cshtml"
                   Write(day);

            
            #line default
            #line hidden
WriteLiteral(". ");

            
            #line 89 "..\..\Views\Report\calender.cshtml"
                         Write(sDay);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 90 "..\..\Views\Report\calender.cshtml"
                }
                else
                {
                    colourRow = "white";

            
            #line default
            #line hidden
WriteLiteral("                    <td>");

            
            #line 94 "..\..\Views\Report\calender.cshtml"
                   Write(day);

            
            #line default
            #line hidden
WriteLiteral(". ");

            
            #line 94 "..\..\Views\Report\calender.cshtml"
                         Write(sDay);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 95 "..\..\Views\Report\calender.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 96 "..\..\Views\Report\calender.cshtml"
                 for (int hour = 0; hour < 24; hour++)
                {
                    List<ViewHeaderBatch> batches = new List<ViewHeaderBatch>();
                    int latestBatchNo = 0;
                    name = string.Empty;
                    if (Model.Data.Exists(p => p.TimeStart.Day == day && p.TimeStart.Hour == hour))
                    {
                        var data = Model.Data.Where(p => p.TimeStart.Day == day && p.TimeStart.Hour == hour && p.RecordType != Operations.DosingOut);
                        foreach (var batch in data)
                        {
                            if (batch.Need != 0)
                            {
                                amnt = batch.Need / 1000;
                                amntTotal += amnt;
                            }
                            if (batch.BatchNo != latestBatchNo && (batch.RecordType == Operations.RecipeStart))
                            {

                                batches.Add(new ViewHeaderBatch() { Name = batch.Destination, BatchNo = batch.BatchNo, AmntTotal = amnt, RecipeNo = batch.Variant1 });
                                count++;
                            }
                            latestBatchNo = batch.BatchNo;
                        }
                    }
                    if (Model.Data.Exists(p => p.TimeStart.Day == day && p.TimeStart.Hour == hour && p.RecordType == Operations.DosingOut))
                    {
                        dosingOutCount = Model.Data.Where(p => p.TimeStart.Day == day && p.TimeStart.Hour == hour && p.RecordType == Operations.DosingOut).Count();
                        dosingOutAmountSum = Model.Data.Where(p => p.TimeStart.Day == day && p.TimeStart.Hour == hour && p.RecordType == Operations.DosingOut).Sum(p => p.Actual);
                        dosingOut = new ViewHeaderDosingOut { hour = hour, count = dosingOutCount, amountSum = dosingOutAmountSum };
                    }
                    if (Model.Data.Exists(p => p.TimeStart.Day == day && p.TimeStart.Hour == hour && (p.RecordType == Operations.FermenterCleaning || p.RecordType == Operations.PipWorkCleaning || p.RecordType == Operations.YeastCleaning)))
                    {
                        var cleanings = Model.Data.Where(p => p.TimeStart.Day == day && p.TimeStart.Hour == hour && (p.RecordType == Operations.FermenterCleaning || p.RecordType == Operations.PipWorkCleaning || p.RecordType == Operations.YeastCleaning));
                        foreach (var cleanOp in cleanings)
                        {
                            if (cleanOp.RecordType == Operations.Pigging)
                            {
                                cleaning = new ViewHeaderCleaning { cleaning = cleanOp.RecordType.ToString(), destination = cleanOp.Destination, BatchNo = cleanOp.BatchNo, ClnType = ClnType.none, StartedBy = (StartedBy)cleanOp.Variant2 };
                            }
                            else
                            {
                                cleaning = new ViewHeaderCleaning { cleaning = cleanOp.RecordType.ToString(), destination = cleanOp.Destination, BatchNo = cleanOp.BatchNo, ClnType = (ClnType)cleanOp.Variant1, StartedBy = (StartedBy)cleanOp.Variant2 };
                            }
                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteAttribute("style", Tuple.Create(" style=\"", 6742), Tuple.Create("\"", 6778)
, Tuple.Create(Tuple.Create("", 6750), Tuple.Create("background-color:", 6750), true)
            
            #line 141 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create(" ", 6767), Tuple.Create<System.Object, System.Int32>(colourRow
            
            #line default
            #line hidden
, 6768), false)
);

WriteLiteral(">\r\n");

            
            #line 142 "..\..\Views\Report\calender.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 142 "..\..\Views\Report\calender.cshtml"
                         foreach (var batch in batches)
                    {
                        if (Model.Data.Exists(p => p.BatchNo == batch.BatchNo && p.RecordType == Operations.RecipeEnd))
                        {
                            EndType = Model.Data.Single(p => p.BatchNo == batch.BatchNo && p.RecordType == Operations.RecipeEnd).Variant2; // takes endType
                        }
                        batch.Status = Convert.ToBoolean(EndType);
                        if (batch.Status != false)
                        {

            
            #line default
            #line hidden
WriteLiteral("                                <b><a");

WriteAttribute("href", Tuple.Create(" href=\"", 7378), Tuple.Create("\"", 7414)
, Tuple.Create(Tuple.Create("", 7385), Tuple.Create("/Report/Detail/", 7385), true)
            
            #line 151 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 7400), Tuple.Create<System.Object, System.Int32>(batch.BatchNo
            
            #line default
            #line hidden
, 7400), false)
);

WriteLiteral(" class=\"batch\"");

WriteLiteral(" style=\"color: darkgreen;\"");

WriteAttribute("title", Tuple.Create(" title=\"", 7455), Tuple.Create("\"", 7544)
, Tuple.Create(Tuple.Create("", 7463), Tuple.Create("Batch:", 7463), true)
            
            #line 151 "..\..\Views\Report\calender.cshtml"
                                                , Tuple.Create(Tuple.Create(" ", 7469), Tuple.Create<System.Object, System.Int32>(batch.BatchNo
            
            #line default
            #line hidden
, 7470), false)
, Tuple.Create(Tuple.Create("  ", 7484), Tuple.Create("Recipe:", 7486), true)
            
            #line 151 "..\..\Views\Report\calender.cshtml"
                                                                        , Tuple.Create(Tuple.Create(" ", 7493), Tuple.Create<System.Object, System.Int32>(batch.RecipeNo
            
            #line default
            #line hidden
, 7494), false)
, Tuple.Create(Tuple.Create(" ", 7509), Tuple.Create("Filled", 7510), true)
, Tuple.Create(Tuple.Create(" ", 7516), Tuple.Create("amount:", 7517), true)
            
            #line 151 "..\..\Views\Report\calender.cshtml"
                                                                                                       , Tuple.Create(Tuple.Create(" ", 7524), Tuple.Create<System.Object, System.Int32>(batch.AmntTotal
            
            #line default
            #line hidden
, 7525), false)
, Tuple.Create(Tuple.Create(" ", 7541), Tuple.Create("kg", 7542), true)
);

WriteLiteral(">");

            
            #line 151 "..\..\Views\Report\calender.cshtml"
                                                                                                                                                                                                        Write(batch.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></b>\r\n");

            
            #line 152 "..\..\Views\Report\calender.cshtml"
                            }
                            else
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <b><a");

WriteAttribute("href", Tuple.Create(" href=\"", 7700), Tuple.Create("\"", 7736)
, Tuple.Create(Tuple.Create("", 7707), Tuple.Create("/Report/Detail/", 7707), true)
            
            #line 155 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 7722), Tuple.Create<System.Object, System.Int32>(batch.BatchNo
            
            #line default
            #line hidden
, 7722), false)
);

WriteLiteral(" class=\"batch\"");

WriteAttribute("title", Tuple.Create(" title=\"", 7751), Tuple.Create("\"", 7840)
, Tuple.Create(Tuple.Create("", 7759), Tuple.Create("Batch:", 7759), true)
            
            #line 155 "..\..\Views\Report\calender.cshtml"
                      , Tuple.Create(Tuple.Create(" ", 7765), Tuple.Create<System.Object, System.Int32>(batch.BatchNo
            
            #line default
            #line hidden
, 7766), false)
, Tuple.Create(Tuple.Create("  ", 7780), Tuple.Create("Recipe:", 7782), true)
            
            #line 155 "..\..\Views\Report\calender.cshtml"
                                              , Tuple.Create(Tuple.Create(" ", 7789), Tuple.Create<System.Object, System.Int32>(batch.RecipeNo
            
            #line default
            #line hidden
, 7790), false)
, Tuple.Create(Tuple.Create(" ", 7805), Tuple.Create("Filled", 7806), true)
, Tuple.Create(Tuple.Create(" ", 7812), Tuple.Create("amount:", 7813), true)
            
            #line 155 "..\..\Views\Report\calender.cshtml"
                                                                             , Tuple.Create(Tuple.Create(" ", 7820), Tuple.Create<System.Object, System.Int32>(batch.AmntTotal
            
            #line default
            #line hidden
, 7821), false)
, Tuple.Create(Tuple.Create(" ", 7837), Tuple.Create("kg", 7838), true)
);

WriteLiteral(">");

            
            #line 155 "..\..\Views\Report\calender.cshtml"
                                                                                                                                                                              Write(batch.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></b>\r\n");

            
            #line 156 "..\..\Views\Report\calender.cshtml"
                            }
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 158 "..\..\Views\Report\calender.cshtml"
                         if (dosingOut != null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 8023), Tuple.Create("\"", 8073)
, Tuple.Create(Tuple.Create("", 8030), Tuple.Create("/ReportDosing/Day/", 8030), true)
            
            #line 160 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 8048), Tuple.Create<System.Object, System.Int32>(day
            
            #line default
            #line hidden
, 8048), false)
, Tuple.Create(Tuple.Create("", 8052), Tuple.Create("/", 8052), true)
            
            #line 160 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 8053), Tuple.Create<System.Object, System.Int32>(ViewBag.Month
            
            #line default
            #line hidden
, 8053), false)
, Tuple.Create(Tuple.Create("", 8067), Tuple.Create("/", 8067), true)
            
            #line 160 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 8068), Tuple.Create<System.Object, System.Int32>(year
            
            #line default
            #line hidden
, 8068), false)
);

WriteLiteral(" class=\"dosing\"");

WriteAttribute("title", Tuple.Create(" title=\"", 8089), Tuple.Create("\"", 8141)
, Tuple.Create(Tuple.Create("", 8097), Tuple.Create("Total", 8097), true)
, Tuple.Create(Tuple.Create(" ", 8102), Tuple.Create("Amount:", 8103), true)
            
            #line 160 "..\..\Views\Report\calender.cshtml"
                                      , Tuple.Create(Tuple.Create(" ", 8110), Tuple.Create<System.Object, System.Int32>(dosingOut.amountSum/1000
            
            #line default
            #line hidden
, 8111), false)
, Tuple.Create(Tuple.Create(" ", 8138), Tuple.Create("kg", 8139), true)
);

WriteLiteral(">(<b>");

            
            #line 160 "..\..\Views\Report\calender.cshtml"
                                                                                                                                                     Write(dosingOut.count);

            
            #line default
            #line hidden
WriteLiteral("</b>)</a>\r\n");

            
            #line 161 "..\..\Views\Report\calender.cshtml"
                            rowDOcount += dosingOut.count;
                            rowDOamount += (dosingOut.amountSum / 1000);
                            dosingOut = null;
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 165 "..\..\Views\Report\calender.cshtml"
                         if (cleaning != null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 8483), Tuple.Create("\"", 8535)
, Tuple.Create(Tuple.Create("", 8490), Tuple.Create("/ReportCleaning/Day/", 8490), true)
            
            #line 167 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 8510), Tuple.Create<System.Object, System.Int32>(day
            
            #line default
            #line hidden
, 8510), false)
, Tuple.Create(Tuple.Create("", 8514), Tuple.Create("/", 8514), true)
            
            #line 167 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 8515), Tuple.Create<System.Object, System.Int32>(ViewBag.Month
            
            #line default
            #line hidden
, 8515), false)
, Tuple.Create(Tuple.Create("", 8529), Tuple.Create("/", 8529), true)
            
            #line 167 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 8530), Tuple.Create<System.Object, System.Int32>(year
            
            #line default
            #line hidden
, 8530), false)
);

WriteLiteral(" class=\"cleaning\"");

WriteAttribute("title", Tuple.Create(" title=\"", 8553), Tuple.Create("\"", 8673)
, Tuple.Create(Tuple.Create("", 8561), Tuple.Create("Cleaning:", 8561), true)
            
            #line 167 "..\..\Views\Report\calender.cshtml"
                                     , Tuple.Create(Tuple.Create(" ", 8570), Tuple.Create<System.Object, System.Int32>(cleaning.cleaning
            
            #line default
            #line hidden
, 8571), false)
, Tuple.Create(Tuple.Create(" ", 8589), Tuple.Create("Clean", 8590), true)
, Tuple.Create(Tuple.Create(" ", 8595), Tuple.Create("Type:", 8596), true)
            
            #line 167 "..\..\Views\Report\calender.cshtml"
                                                                    , Tuple.Create(Tuple.Create(" ", 8601), Tuple.Create<System.Object, System.Int32>(cleaning.ClnType.ToString()
            
            #line default
            #line hidden
, 8602), false)
, Tuple.Create(Tuple.Create(" ", 8630), Tuple.Create("Started", 8631), true)
, Tuple.Create(Tuple.Create(" ", 8638), Tuple.Create("By:", 8639), true)
            
            #line 167 "..\..\Views\Report\calender.cshtml"
                                                                                                             , Tuple.Create(Tuple.Create(" ", 8642), Tuple.Create<System.Object, System.Int32>(cleaning.StartedBy.ToString()
            
            #line default
            #line hidden
, 8643), false)
);

WriteLiteral(">[<b>");

            
            #line 167 "..\..\Views\Report\calender.cshtml"
                                                                                                                                                                                                                             Write(cleaning.destination);

            
            #line default
            #line hidden
WriteLiteral("</b>]</a>\r\n");

            
            #line 168 "..\..\Views\Report\calender.cshtml"
                            cleaning = null;
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </td>\r\n");

            
            #line 171 "..\..\Views\Report\calender.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 172 "..\..\Views\Report\calender.cshtml"
                 if (count != 0)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" style=\"background-color: lightcyan; text-align: center;\"");

WriteLiteral(">");

            
            #line 174 "..\..\Views\Report\calender.cshtml"
                                                                            Write(count);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 175 "..\..\Views\Report\calender.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" style=\"background-color: lightcyan; text-align: center;\"");

WriteLiteral("></td>\r\n");

            
            #line 179 "..\..\Views\Report\calender.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 180 "..\..\Views\Report\calender.cshtml"
                  countOverall += count; count = 0; 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 181 "..\..\Views\Report\calender.cshtml"
                
            
            #line default
            #line hidden
            
            #line 181 "..\..\Views\Report\calender.cshtml"
                 if (rowDOcount != 0)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" style=\"background-color: lightcyan; text-align: center; \"");

WriteLiteral(">");

            
            #line 183 "..\..\Views\Report\calender.cshtml"
                                                                             Write(rowDOcount);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 184 "..\..\Views\Report\calender.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" style=\"background-color: lightcyan; text-align: center;\"");

WriteLiteral("></td>\r\n");

            
            #line 188 "..\..\Views\Report\calender.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 189 "..\..\Views\Report\calender.cshtml"
                   rowDOcountOverall += rowDOcount; rowDOcount = 0; 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 190 "..\..\Views\Report\calender.cshtml"
                
            
            #line default
            #line hidden
            
            #line 190 "..\..\Views\Report\calender.cshtml"
                 if (amntTotal != 0)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" style=\"background-color: lightgray; text-align: center; \"");

WriteLiteral(">");

            
            #line 192 "..\..\Views\Report\calender.cshtml"
                                                                             Write(amntTotal);

            
            #line default
            #line hidden
WriteLiteral(" kg</td>\r\n");

            
            #line 193 "..\..\Views\Report\calender.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" style=\"background-color: lightgray; text-align: center;\"");

WriteLiteral("></td>\r\n");

            
            #line 197 "..\..\Views\Report\calender.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 198 "..\..\Views\Report\calender.cshtml"
                  amntOverall += amntTotal; amntTotal = 0; 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 199 "..\..\Views\Report\calender.cshtml"
                
            
            #line default
            #line hidden
            
            #line 199 "..\..\Views\Report\calender.cshtml"
                 if (rowDOamount != 0)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" style=\"background-color: lightgray; text-align: center; \"");

WriteLiteral(">");

            
            #line 201 "..\..\Views\Report\calender.cshtml"
                                                                             Write(rowDOamount);

            
            #line default
            #line hidden
WriteLiteral(" kg</td>\r\n");

            
            #line 202 "..\..\Views\Report\calender.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" style=\"background-color: lightgray; text-align: center;\"");

WriteLiteral("></td>\r\n");

            
            #line 206 "..\..\Views\Report\calender.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 207 "..\..\Views\Report\calender.cshtml"
                   rowDOamountOverall += rowDOamount; rowDOamount = 0; 
            
            #line default
            #line hidden
WriteLiteral("\r\n            </tr>\r\n");

            
            #line 209 "..\..\Views\Report\calender.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n        <td><b>Total</b></td>\r\n");

            
            #line 212 "..\..\Views\Report\calender.cshtml"
        
            
            #line default
            #line hidden
            
            #line 212 "..\..\Views\Report\calender.cshtml"
         for (int hours = 0; hours < 24; hours++)
        {

            
            #line default
            #line hidden
WriteLiteral("            <td");

WriteLiteral(" class=\"th-Report\"");

WriteLiteral("></td>\r\n");

            
            #line 215 "..\..\Views\Report\calender.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <td");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral("><b>");

            
            #line 216 "..\..\Views\Report\calender.cshtml"
                                      Write(countOverall);

            
            #line default
            #line hidden
WriteLiteral("</b></td>\r\n        <td");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral("><b>");

            
            #line 217 "..\..\Views\Report\calender.cshtml"
                                      Write(rowDOcountOverall);

            
            #line default
            #line hidden
WriteLiteral("</b></td>\r\n        <td");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral("><b>");

            
            #line 218 "..\..\Views\Report\calender.cshtml"
                                      Write(amntOverall);

            
            #line default
            #line hidden
WriteLiteral(" kg</b></td>\r\n        <td");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral("><b>");

            
            #line 219 "..\..\Views\Report\calender.cshtml"
                                      Write(rowDOamountOverall);

            
            #line default
            #line hidden
WriteLiteral(" kg</b></td>\r\n    </tr>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
