#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\Views\Report\calender.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    
    #line 1 "..\..\Views\Report\calender.cshtml"
    using System.Threading;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using KneaderPrototype;
    using KneaderPrototype.Controllers;
    
    #line 3 "..\..\Views\Report\calender.cshtml"
    using KneaderPrototype.Report.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Report/calender.cshtml")]
    public partial class _Views_Report_calender_cshtml : System.Web.Mvc.WebViewPage<KneaderPrototype.Report.Models.DataReportModel>
    {
        public _Views_Report_calender_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Views\Report\calender.cshtml"
  
    ViewBag.Title = "calender";
    string name = string.Empty;
    int EndType = 0;
    int amntTotal = 0;
    int amntOverall= 0;
    int amnt = 0;
    string colourRow = "white";
    int count = 0;
    int countOverall = 0;
    int dosingOutCount = 0;
    int dosingOutAmountSum = 0;
    int rowDOcount = 0;
    int rowDOamount = 0;
    int rowDOcountOverall = 0;
    int rowDOamountOverall = 0;
    int cleaningCount = 0;
    /*
    int rowDOcount = 0;
    int rowDOamount = 0;
    int rowDOcountOverall = 0;
    int rowDOamountOverall = 0;
    */
    int year = ViewBag.year;
    int monthLess = ViewBag.Month - 1;
    int monthMore = ViewBag.Month + 1;
    if (monthLess < 1) {
        year--;
        monthLess = 12;
    }
    if (monthMore > 12) {
        year++;
        monthMore = 1;
    }
    ViewHeaderDosingOut dosingOut = null;
    ViewHeaderCleaning cleaning = null;
    Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");
    DateTime monthDT = new DateTime(year, ViewBag.month, 1);
    string monthName = monthDT.ToString("MMMM");


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h4>Calender</h4>\r\n<div");

WriteLiteral(" class=\" col-md-12\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" class=\"btn-primary btn-xs\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1340), Tuple.Create("\"", 1377)
, Tuple.Create(Tuple.Create("", 1347), Tuple.Create("/Report/Month/", 1347), true)
            
            #line 50 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 1361), Tuple.Create<System.Object, System.Int32>(monthLess
            
            #line default
            #line hidden
, 1361), false)
, Tuple.Create(Tuple.Create("", 1371), Tuple.Create("/", 1371), true)
            
            #line 50 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 1372), Tuple.Create<System.Object, System.Int32>(year
            
            #line default
            #line hidden
, 1372), false)
);

WriteLiteral(">-1 month</a> Month: ");

            
            #line 50 "..\..\Views\Report\calender.cshtml"
                                                                                       Write(monthName);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 50 "..\..\Views\Report\calender.cshtml"
                                                                                                  Write(year);

            
            #line default
            #line hidden
WriteLiteral(" <a");

WriteLiteral(" class=\"btn-primary btn-xs\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1445), Tuple.Create("\"", 1482)
, Tuple.Create(Tuple.Create("", 1452), Tuple.Create("/Report/Month/", 1452), true)
            
            #line 50 "..\..\Views\Report\calender.cshtml"
                                                                               , Tuple.Create(Tuple.Create("", 1466), Tuple.Create<System.Object, System.Int32>(monthMore
            
            #line default
            #line hidden
, 1466), false)
, Tuple.Create(Tuple.Create("", 1476), Tuple.Create("/", 1476), true)
            
            #line 50 "..\..\Views\Report\calender.cshtml"
                                                                                          , Tuple.Create(Tuple.Create("", 1477), Tuple.Create<System.Object, System.Int32>(year
            
            #line default
            #line hidden
, 1477), false)
);

WriteLiteral(">+1 month</a>\r\n    <p></p>\r\n</div>\r\n<div");

WriteLiteral(" class=\" col-md-12\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"checkbox-inline big-checkbox\"");

WriteLiteral(">\r\n        <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" onclick=\"hideShowBatches()\"");

WriteLiteral("/>Hide/Show Batches\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"checkbox-inline big-checkbox\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" onclick=\"hideShowDosing()\"");

WriteLiteral(" checked/>Hide/Show Dosing\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"checkbox-inline big-checkbox\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" onclick=\"hideShowCleaning()\"");

WriteLiteral(" checked/>Hide/Show Cleaning\r\n    </div>\r\n</div>\r\n<table");

WriteLiteral(" class=\"table-bordered table-condensed\"");

WriteLiteral(">\r\n    <thead>\r\n    <tr>\r\n        <th>Day | Hours</th>\r\n");

            
            #line 68 "..\..\Views\Report\calender.cshtml"
        
            
            #line default
            #line hidden
            
            #line 68 "..\..\Views\Report\calender.cshtml"
         for (int hours = 0;hours<24;hours++) {

            
            #line default
            #line hidden
WriteLiteral("            <th");

WriteLiteral(" class=\"th-Report\"");

WriteLiteral(">");

            
            #line 69 "..\..\Views\Report\calender.cshtml"
                             Write(hours);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n");

            
            #line 70 "..\..\Views\Report\calender.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <th");

WriteLiteral(" style=\"background-color: lightcyan;\"");

WriteLiteral(" title=\"Batches Count\"");

WriteLiteral(">B. cnt.</th>\r\n        <th");

WriteLiteral(" style=\"background-color: lightcyan;\"");

WriteLiteral(" title=\"Dosing Count\"");

WriteLiteral(">DO. cnt.</th>\r\n        <th");

WriteLiteral(" style=\"background-color: lightgray;\"");

WriteLiteral(" title=\"Batches amount\"");

WriteLiteral(">B. amt.</th>       \r\n        <th");

WriteLiteral(" style=\"background-color: lightgray;\"");

WriteLiteral(" title=\"Dosing amount\"");

WriteLiteral(">DO. amt.</th>\r\n    </tr>\r\n    </thead>\r\n");

            
            #line 77 "..\..\Views\Report\calender.cshtml"
    
            
            #line default
            #line hidden
            
            #line 77 "..\..\Views\Report\calender.cshtml"
     for (int day = 1; day <= DateTime.DaysInMonth(year, ViewBag.month); day++)
    {
        
            
            #line default
            #line hidden
            
            #line 79 "..\..\Views\Report\calender.cshtml"
           DateTime dayDT = new DateTime(year, ViewBag.month, day); string sDay = dayDT.DayOfWeek.ToString();  
            
            #line default
            #line hidden
            
            #line 79 "..\..\Views\Report\calender.cshtml"
                                                                                                                

            
            #line default
            #line hidden
WriteLiteral("        <tr>\r\n");

            
            #line 81 "..\..\Views\Report\calender.cshtml"
            
            
            #line default
            #line hidden
            
            #line 81 "..\..\Views\Report\calender.cshtml"
             if (dayDT.DayOfWeek == DayOfWeek.Saturday || dayDT.DayOfWeek == DayOfWeek.Sunday)
            {
                colourRow = "lightgoldenrodyellow";

            
            #line default
            #line hidden
WriteLiteral("                <td>");

            
            #line 84 "..\..\Views\Report\calender.cshtml"
               Write(day);

            
            #line default
            #line hidden
WriteLiteral(". ");

            
            #line 84 "..\..\Views\Report\calender.cshtml"
                     Write(sDay);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 85 "..\..\Views\Report\calender.cshtml"
            } else
            {
                colourRow = "white";

            
            #line default
            #line hidden
WriteLiteral("                <td>");

            
            #line 88 "..\..\Views\Report\calender.cshtml"
               Write(day);

            
            #line default
            #line hidden
WriteLiteral(". ");

            
            #line 88 "..\..\Views\Report\calender.cshtml"
                     Write(sDay);

            
            #line default
            #line hidden
WriteLiteral("</td>            \r\n");

            
            #line 89 "..\..\Views\Report\calender.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("           ");

            
            #line 90 "..\..\Views\Report\calender.cshtml"
            for (int hour = 0; hour < 24; hour++)
           {
               List<ViewHeaderBatch> batches = new List<ViewHeaderBatch>();
               int latestBatchNo = 0;
               name = string.Empty;
               if (Model.Data.Exists(p => p.TimeStart.Day == day && p.TimeStart.Hour == hour))
               {
                   var data = Model.Data.Where(p => p.TimeStart.Day == day && p.TimeStart.Hour == hour && p.RecordType != Operations.DosingOut);
                   foreach (var batch in data)
                   {
                       if (batch.Need != 0)
                       {
                           amnt = batch.Need / 1000;
                           amntTotal += amnt;
                       }
                       if (batch.BatchNo != latestBatchNo && (batch.RecordType == Operations.RecipeStart))
                       {

                           batches.Add(new ViewHeaderBatch() { Name = batch.Destination, BatchNo = batch.BatchNo, AmntTotal = amnt, RecipeNo = batch.Variant1});
                           count++;
                       }
                       latestBatchNo = batch.BatchNo;
                   }
               }
               if (Model.Data.Exists(p => p.TimeStart.Day == day && p.TimeStart.Hour == hour && p.RecordType == Operations.DosingOut))
               {
                   dosingOutCount = Model.Data.Where(p => p.TimeStart.Day == day && p.TimeStart.Hour == hour && p.RecordType == Operations.DosingOut).Count();
                   dosingOutAmountSum = Model.Data.Where(p => p.TimeStart.Day == day && p.TimeStart.Hour == hour && p.RecordType == Operations.DosingOut).Sum(p => p.Actual);
                   dosingOut = new ViewHeaderDosingOut { hour = hour, count = dosingOutCount, amountSum = dosingOutAmountSum};
               }
               if (Model.Data.Exists(p => p.TimeStart.Day == day && p.TimeStart.Hour == hour && (p.RecordType == Operations.FermenterCleaning || p.RecordType == Operations.PipWorkCleaning || p.RecordType == Operations.YeastCleaning)))
               {
                   var cleanings = Model.Data.Where(p => p.TimeStart.Day == day && p.TimeStart.Hour == hour && (p.RecordType == Operations.FermenterCleaning || p.RecordType == Operations.PipWorkCleaning || p.RecordType == Operations.YeastCleaning));
                   foreach (var cleanOp in cleanings) {
                       if (cleanOp.RecordType == Operations.Pigging) {
                           cleaning = new ViewHeaderCleaning { cleaning = cleanOp.RecordType.ToString(), destination = cleanOp.Destination, BatchNo = cleanOp.BatchNo, ClnType = ClnType.none, StartedBy = (StartedBy)cleanOp.Variant2 };
                       }
                       else {
                           cleaning = new ViewHeaderCleaning { cleaning = cleanOp.RecordType.ToString(), destination = cleanOp.Destination, BatchNo = cleanOp.BatchNo, ClnType = (ClnType)cleanOp.Variant1, StartedBy = (StartedBy)cleanOp.Variant2 };
                       }
                   }
               }

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteAttribute("style", Tuple.Create(" style=\"", 6228), Tuple.Create("\"", 6264)
, Tuple.Create(Tuple.Create("", 6236), Tuple.Create("background-color:", 6236), true)
            
            #line 132 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create(" ", 6253), Tuple.Create<System.Object, System.Int32>(colourRow
            
            #line default
            #line hidden
, 6254), false)
);

WriteLiteral(">\r\n");

            
            #line 133 "..\..\Views\Report\calender.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 133 "..\..\Views\Report\calender.cshtml"
                     foreach (var batch in batches)
                    {
                        if (Model.Data.Exists(p => p.BatchNo == batch.BatchNo && p.RecordType == Operations.RecipeEnd))
                        {
                            EndType = Model.Data.Single(p => p.BatchNo == batch.BatchNo && p.RecordType == Operations.RecipeEnd).Variant2; // takes endType
                        }
                        batch.Status = Convert.ToBoolean(EndType);
                        if (batch.Status != false)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <b><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6856), Tuple.Create("\"", 6892)
, Tuple.Create(Tuple.Create("", 6863), Tuple.Create("/Report/Detail/", 6863), true)
            
            #line 142 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 6878), Tuple.Create<System.Object, System.Int32>(batch.BatchNo
            
            #line default
            #line hidden
, 6878), false)
);

WriteLiteral(" class=\"batch\"");

WriteLiteral(" style=\"color: darkgreen;\"");

WriteAttribute("title", Tuple.Create(" title=\"", 6933), Tuple.Create("\"", 7022)
, Tuple.Create(Tuple.Create("", 6941), Tuple.Create("Batch:", 6941), true)
            
            #line 142 "..\..\Views\Report\calender.cshtml"
                                            , Tuple.Create(Tuple.Create(" ", 6947), Tuple.Create<System.Object, System.Int32>(batch.BatchNo
            
            #line default
            #line hidden
, 6948), false)
, Tuple.Create(Tuple.Create("  ", 6962), Tuple.Create("Recipe:", 6964), true)
            
            #line 142 "..\..\Views\Report\calender.cshtml"
                                                                    , Tuple.Create(Tuple.Create(" ", 6971), Tuple.Create<System.Object, System.Int32>(batch.RecipeNo
            
            #line default
            #line hidden
, 6972), false)
, Tuple.Create(Tuple.Create(" ", 6987), Tuple.Create("Filled", 6988), true)
, Tuple.Create(Tuple.Create(" ", 6994), Tuple.Create("amount:", 6995), true)
            
            #line 142 "..\..\Views\Report\calender.cshtml"
                                                                                                   , Tuple.Create(Tuple.Create(" ", 7002), Tuple.Create<System.Object, System.Int32>(batch.AmntTotal
            
            #line default
            #line hidden
, 7003), false)
, Tuple.Create(Tuple.Create(" ", 7019), Tuple.Create("kg", 7020), true)
);

WriteLiteral(">");

            
            #line 142 "..\..\Views\Report\calender.cshtml"
                                                                                                                                                                                                    Write(batch.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></b>\r\n");

            
            #line 143 "..\..\Views\Report\calender.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <b><a");

WriteAttribute("href", Tuple.Create(" href=\"", 7162), Tuple.Create("\"", 7198)
, Tuple.Create(Tuple.Create("", 7169), Tuple.Create("/Report/Detail/", 7169), true)
            
            #line 146 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 7184), Tuple.Create<System.Object, System.Int32>(batch.BatchNo
            
            #line default
            #line hidden
, 7184), false)
);

WriteLiteral(" class=\"batch\"");

WriteAttribute("title", Tuple.Create(" title=\"", 7213), Tuple.Create("\"", 7302)
, Tuple.Create(Tuple.Create("", 7221), Tuple.Create("Batch:", 7221), true)
            
            #line 146 "..\..\Views\Report\calender.cshtml"
                  , Tuple.Create(Tuple.Create(" ", 7227), Tuple.Create<System.Object, System.Int32>(batch.BatchNo
            
            #line default
            #line hidden
, 7228), false)
, Tuple.Create(Tuple.Create("  ", 7242), Tuple.Create("Recipe:", 7244), true)
            
            #line 146 "..\..\Views\Report\calender.cshtml"
                                          , Tuple.Create(Tuple.Create(" ", 7251), Tuple.Create<System.Object, System.Int32>(batch.RecipeNo
            
            #line default
            #line hidden
, 7252), false)
, Tuple.Create(Tuple.Create(" ", 7267), Tuple.Create("Filled", 7268), true)
, Tuple.Create(Tuple.Create(" ", 7274), Tuple.Create("amount:", 7275), true)
            
            #line 146 "..\..\Views\Report\calender.cshtml"
                                                                         , Tuple.Create(Tuple.Create(" ", 7282), Tuple.Create<System.Object, System.Int32>(batch.AmntTotal
            
            #line default
            #line hidden
, 7283), false)
, Tuple.Create(Tuple.Create(" ", 7299), Tuple.Create("kg", 7300), true)
);

WriteLiteral(">");

            
            #line 146 "..\..\Views\Report\calender.cshtml"
                                                                                                                                                                          Write(batch.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></b>\r\n");

            
            #line 147 "..\..\Views\Report\calender.cshtml"
                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 149 "..\..\Views\Report\calender.cshtml"
                     if (dosingOut != null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 7469), Tuple.Create("\"", 7519)
, Tuple.Create(Tuple.Create("", 7476), Tuple.Create("/ReportDosing/Day/", 7476), true)
            
            #line 151 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 7494), Tuple.Create<System.Object, System.Int32>(day
            
            #line default
            #line hidden
, 7494), false)
, Tuple.Create(Tuple.Create("", 7498), Tuple.Create("/", 7498), true)
            
            #line 151 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 7499), Tuple.Create<System.Object, System.Int32>(ViewBag.Month
            
            #line default
            #line hidden
, 7499), false)
, Tuple.Create(Tuple.Create("", 7513), Tuple.Create("/", 7513), true)
            
            #line 151 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 7514), Tuple.Create<System.Object, System.Int32>(year
            
            #line default
            #line hidden
, 7514), false)
);

WriteLiteral(" class=\"dosing\"");

WriteAttribute("title", Tuple.Create(" title=\"", 7535), Tuple.Create("\"", 7587)
, Tuple.Create(Tuple.Create("", 7543), Tuple.Create("Total", 7543), true)
, Tuple.Create(Tuple.Create(" ", 7548), Tuple.Create("Amount:", 7549), true)
            
            #line 151 "..\..\Views\Report\calender.cshtml"
                                  , Tuple.Create(Tuple.Create(" ", 7556), Tuple.Create<System.Object, System.Int32>(dosingOut.amountSum/1000
            
            #line default
            #line hidden
, 7557), false)
, Tuple.Create(Tuple.Create(" ", 7584), Tuple.Create("kg", 7585), true)
);

WriteLiteral(">(<b>");

            
            #line 151 "..\..\Views\Report\calender.cshtml"
                                                                                                                                                 Write(dosingOut.count);

            
            #line default
            #line hidden
WriteLiteral("</b>)</a>\r\n");

            
            #line 152 "..\..\Views\Report\calender.cshtml"
                        rowDOcount += dosingOut.count;
                        rowDOamount += (dosingOut.amountSum/1000);
                        dosingOut = null;
                    }

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 156 "..\..\Views\Report\calender.cshtml"
                     if (cleaning != null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 7903), Tuple.Create("\"", 7955)
, Tuple.Create(Tuple.Create("", 7910), Tuple.Create("/ReportCleaning/Day/", 7910), true)
            
            #line 158 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 7930), Tuple.Create<System.Object, System.Int32>(day
            
            #line default
            #line hidden
, 7930), false)
, Tuple.Create(Tuple.Create("", 7934), Tuple.Create("/", 7934), true)
            
            #line 158 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 7935), Tuple.Create<System.Object, System.Int32>(ViewBag.Month
            
            #line default
            #line hidden
, 7935), false)
, Tuple.Create(Tuple.Create("", 7949), Tuple.Create("/", 7949), true)
            
            #line 158 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 7950), Tuple.Create<System.Object, System.Int32>(year
            
            #line default
            #line hidden
, 7950), false)
);

WriteLiteral(" class=\"cleaning\"");

WriteAttribute("title", Tuple.Create(" title=\"", 7973), Tuple.Create("\"", 8093)
, Tuple.Create(Tuple.Create("", 7981), Tuple.Create("Cleaning:", 7981), true)
            
            #line 158 "..\..\Views\Report\calender.cshtml"
                                 , Tuple.Create(Tuple.Create(" ", 7990), Tuple.Create<System.Object, System.Int32>(cleaning.cleaning
            
            #line default
            #line hidden
, 7991), false)
, Tuple.Create(Tuple.Create(" ", 8009), Tuple.Create("Clean", 8010), true)
, Tuple.Create(Tuple.Create(" ", 8015), Tuple.Create("Type:", 8016), true)
            
            #line 158 "..\..\Views\Report\calender.cshtml"
                                                                , Tuple.Create(Tuple.Create(" ", 8021), Tuple.Create<System.Object, System.Int32>(cleaning.ClnType.ToString()
            
            #line default
            #line hidden
, 8022), false)
, Tuple.Create(Tuple.Create(" ", 8050), Tuple.Create("Started", 8051), true)
, Tuple.Create(Tuple.Create(" ", 8058), Tuple.Create("By:", 8059), true)
            
            #line 158 "..\..\Views\Report\calender.cshtml"
                                                                                                         , Tuple.Create(Tuple.Create(" ", 8062), Tuple.Create<System.Object, System.Int32>(cleaning.StartedBy.ToString()
            
            #line default
            #line hidden
, 8063), false)
);

WriteLiteral(">[<b>");

            
            #line 158 "..\..\Views\Report\calender.cshtml"
                                                                                                                                                                                                                         Write(cleaning.destination);

            
            #line default
            #line hidden
WriteLiteral("</b>]</a>\r\n");

            
            #line 159 "..\..\Views\Report\calender.cshtml"
                        cleaning = null;
                    }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n");

            
            #line 162 "..\..\Views\Report\calender.cshtml"
           }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 163 "..\..\Views\Report\calender.cshtml"
             if (count != 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral("  style=\"background-color: lightcyan; text-align: center;\"");

WriteLiteral(">");

            
            #line 165 "..\..\Views\Report\calender.cshtml"
                                                                         Write(count);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 166 "..\..\Views\Report\calender.cshtml"
            } else {

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" style=\"background-color: lightcyan; text-align: center;\"");

WriteLiteral("></td>\r\n");

            
            #line 168 "..\..\Views\Report\calender.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 169 "..\..\Views\Report\calender.cshtml"
              countOverall += count; count = 0; 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 170 "..\..\Views\Report\calender.cshtml"
            
            
            #line default
            #line hidden
            
            #line 170 "..\..\Views\Report\calender.cshtml"
             if (rowDOcount != 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" style=\"background-color: lightcyan; text-align: center; \"");

WriteLiteral(">");

            
            #line 172 "..\..\Views\Report\calender.cshtml"
                                                                         Write(rowDOcount);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 173 "..\..\Views\Report\calender.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" style=\"background-color: lightcyan; text-align: center;\"");

WriteLiteral("></td>\r\n");

            
            #line 177 "..\..\Views\Report\calender.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 178 "..\..\Views\Report\calender.cshtml"
               rowDOcountOverall += rowDOcount; rowDOcount = 0; 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 179 "..\..\Views\Report\calender.cshtml"
            
            
            #line default
            #line hidden
            
            #line 179 "..\..\Views\Report\calender.cshtml"
             if (amntTotal != 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" style=\"background-color: lightgray; text-align: center; \"");

WriteLiteral(">");

            
            #line 181 "..\..\Views\Report\calender.cshtml"
                                                                         Write(amntTotal);

            
            #line default
            #line hidden
WriteLiteral(" kg</td>\r\n");

            
            #line 182 "..\..\Views\Report\calender.cshtml"
            } else {

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" style=\"background-color: lightgray; text-align: center;\"");

WriteLiteral("></td>\r\n");

            
            #line 184 "..\..\Views\Report\calender.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 185 "..\..\Views\Report\calender.cshtml"
              amntOverall += amntTotal; amntTotal = 0; 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 186 "..\..\Views\Report\calender.cshtml"
            
            
            #line default
            #line hidden
            
            #line 186 "..\..\Views\Report\calender.cshtml"
             if (rowDOamount != 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" style=\"background-color: lightgray; text-align: center; \"");

WriteLiteral(">");

            
            #line 188 "..\..\Views\Report\calender.cshtml"
                                                                         Write(rowDOamount);

            
            #line default
            #line hidden
WriteLiteral(" kg</td>\r\n");

            
            #line 189 "..\..\Views\Report\calender.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" style=\"background-color: lightgray; text-align: center;\"");

WriteLiteral("></td>\r\n");

            
            #line 193 "..\..\Views\Report\calender.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 194 "..\..\Views\Report\calender.cshtml"
               rowDOamountOverall += rowDOamount; rowDOamount = 0; 
            
            #line default
            #line hidden
WriteLiteral("\r\n        </tr>\r\n");

            
            #line 196 "..\..\Views\Report\calender.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n        <td><b>Total</b></td>\r\n");

            
            #line 199 "..\..\Views\Report\calender.cshtml"
        
            
            #line default
            #line hidden
            
            #line 199 "..\..\Views\Report\calender.cshtml"
         for (int hours = 0; hours < 24; hours++)
        {

            
            #line default
            #line hidden
WriteLiteral("            <td");

WriteLiteral(" class=\"th-Report\"");

WriteLiteral("></td>\r\n");

            
            #line 202 "..\..\Views\Report\calender.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <td");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral("><b>");

            
            #line 203 "..\..\Views\Report\calender.cshtml"
                                      Write(countOverall);

            
            #line default
            #line hidden
WriteLiteral("</b></td>\r\n        <td");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral("><b>");

            
            #line 204 "..\..\Views\Report\calender.cshtml"
                                      Write(rowDOcountOverall);

            
            #line default
            #line hidden
WriteLiteral("</b></td>\r\n        <td");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral("><b>");

            
            #line 205 "..\..\Views\Report\calender.cshtml"
                                      Write(amntOverall);

            
            #line default
            #line hidden
WriteLiteral(" kg</b></td>\r\n        <td");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral("><b>");

            
            #line 206 "..\..\Views\Report\calender.cshtml"
                                      Write(rowDOamountOverall);

            
            #line default
            #line hidden
WriteLiteral(" kg</b></td>\r\n    </tr>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
