#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using KneaderPrototype;
    using KneaderPrototype.Controllers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Demo/Index.cshtml")]
    public partial class _Views_Demo_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Demo_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\Demo\Index.cshtml"
  
    ViewBag.Title = "Scheme demo";

            
            #line default
            #line hidden
WriteLiteral(@"
<script>
    var clicked = false;
    $('#scheme').attr(""src"", ""../img/scheme_1.png"");
    function clickAble() {
        if (clicked == true) {
            clicked = false;
            $('#scheme').attr(""src"", ""../img/scheme_2.png"");
        } else {
            clicked = true;
            $('#scheme').attr(""src"", ""../img/scheme_1.png"");
        }
    }
</script>
<h2>Scheme from HMI panel</h2>
<img");

WriteLiteral(" id=\"scheme\"");

WriteLiteral(" onclick=\"clickAble()\"");

WriteLiteral(" src=\"../img/scheme_1.png\"");

WriteLiteral("/>\r\n");

        }
    }
}
#pragma warning restore 1591
